// <auto-generated />
namespace WEBTP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addWEBTPMigr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addWEBTPMigr));
        
        string IMigrationMetadata.Id
        {
            get { return "202102231008028_addWEBTPMigr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
